# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b9aea0630be2e533e4a3374e4184d29cfc1f2c1e21b9dd5cba106289406302470fe93818646ebf21ad1bcff01c3e1372c6c65c75f3347a546164a96360f62b9

test:
  secret_key_base: 52fe61f94126c338b383102521ecf3b5f60a164d01878df422dd52d72c8816b9b4e8f9645b1b15e5d67f0f3529ff7e3358d30e3d86f56f0650d44e5895eadb02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
